### ISSUE TITLE
Issues with OneSync Infinity / Beyond 

### ISSUE THREAD

**Issue by ADRNALN** [TheWolfBadger/PoliceEMSActivity#2]
When running onesync_beyond the blips only register on your map when you're 500 meters or < from another player with their blip on. This works perfectly fine on regular onesync just not one onesync beyond.

I think its mainly due to how onesync infinity uses player culling

**Comment by JaredScar** [comment]
I probably won't fix this, so hopefully someone makes a pull request or another branch fixing it.
