### ISSUE TITLE
Duty is not giving the right role.

### ISSUE THREAD

**Issue by Brandjuh** [TheWolfBadger/PoliceEMSActivity#3]
Hello,

When I want go on duty as a LSPD,, the system is still logging me in as admin. 
I hope you can fix this :-)

**Comment by JaredScar** [comment]
What do you mean as an Admin?

**Comment by Brandjuh** [comment]
I have set up a few roles that are synced with discord. Those roles are
displayed in the chatmenu fine.
example:

```/bliptag
1 = admin
2 = fire
3 = cop
```

when I do /duty 1 I get the admin role. However if I do the /duty 2 I do
not get the fire role but the admin role. Tested it with a few different
people.

Op di 16 jun. 2020 om 02:17 schreef Jared <notifications@github.com>:

**Comment by JaredScar** [comment]
You have set something up wrong. I've never had any issues with this script

**Comment by Brandjuh** [comment]
It looks like it is always takes the last role in /bliptag

roleList = {
['👮 SAHP | '] = {720178061307412580, 3, '[redacted]'},
['👮 BCSO | '] = {720178300596649994, 5, ' [redacted] '},
['👮 LSPD | '] = {720179435491295272, 3, ' [redacted] '},
['👨‍🚒 SAFR | '] = {720204204504776704, 17, ' [redacted] '},
['👮 SADOC | '] = {721121181201203330, 2, ' [redacted] '},
['🎖️ Admin | '] = {720175684596531321, 1, ' [redacted] '},
}

I do not have problems with DiscordChatTag.

**Comment by JaredScar** [comment]
The command is /bliptag <id>, not /duty <id>

**Comment by Brandjuh** [comment]
A I understand the system now. You need to tune in the right bliptag and then do duty. 

Thanks for the help :)
